---
# Purpose:
#
#   1. Designate which device controls the boiler - must have name "Boiler
#      switch" or "Home Thermostat"
#   2. Give names to radiators which appear in logs and, importantly,
#      prometheus time-series data 
#
# Format:
#
#   $SERIAL_STR: $NAME_STR
#
# Notes
#
#   1. Serial strings should all be 6 characters long, excluding quotes
#   2. Serial strings which are only numbers should be enclosed in quotes
#   3. Numeric serial strings which start with a zero MUST be quoted
#
# Examples
#
# 1A2B3C:Device with unquoted serial string
# '1A2B3C':Device with quoted serial string
# '123456':Device with numeric serial string
# '012345':Device with numeric serial string with leading zero
#
807102: Home Thermostat
2059DA: Energy monitor
B686CA: Living room
2366CA: Hall
7036CA: Toilet
D466CA: Conservatory
188CCA: Bedroom
4E86CA: Christi
BF6BCA: Mark
