---
# Purpose:
#
#   1. Designate which device controls the boiler - must have name "Boiler
#      switch"
#   2. Give names to radiators which appear in logs and, importantly,
#      prometheus time-series data 
#
# Format:
#
#   $SERIAL_STR: $NAME_STR
#
9993FE: Boiler switch
5FC502: Lounge
DBC302: Playroom
DCC302: Hallway
47C702: Front door
CB3FFE: Small bedroom
67C702: Back bedroom
24C702: Master bedroom
